services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PUBLIC_APP_ENV=${PUBLIC_APP_ENV:-development}
      #  postgres://root:mysecretpassword@localhost:5432/local
      - DATABASE_URL=postgresql://root:mysecretpassword@db:5432/local
      - VITE_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        echo '⏳ Waiting for PostgreSQL...' &&
        npm run db:generate &&
        npm run db:migrate &&
        npm run dev
      "

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
