services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PUBLIC_APP_ENV=${PUBLIC_APP_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - VITE_HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
